export { default as vlButton } from './vlButton'
export { default as vlSelect } from './vlSelect'
export { default as vlSwitch } from './vlSwitch'
export { default as vlCheckbox } from './vlCheckBox'
export { default as vlRadio } from './vlRadio'
export { default as vlInput } from './vlInput'
export { default as vlTabs } from './vlTabs'
export { default as vlSlider } from './vlSlider'
export { default as vlInputNumber } from './vlInputNumber'
export { default as vlTooltip } from './vlTooltip'
export { default as vlUpload } from './vlUpload'
export { default as vlPopup } from './vlPopup'
export { default as vlAlert } from './vlAlert'
export { default as vlChip } from './vlChip'
export { default as vlProgress } from './vlProgress'
export { default as vlCard } from './vlCard'
export { default as vlList } from './vlList'
export { default as vlAvatar } from './vlAvatar'
export { default as vlPagination } from './vlPagination'
export { default as vlBreadcrumb } from './vlBreadcrumb'
export { default as vlPrompt } from './vlPrompt'
export { default as vlDivider } from './vlDivider'
export { default as vlSpacer } from './vlSpacer'
export { default as vlIcon } from './vlIcon'
export { default as vlNavbar } from './vlNavbar'
export { default as vlSideBar } from './vlSideBar'
export { default as vlDropDown } from './vlDropDown'
export { default as vlTable } from './vlTable'
export { default as vlTextarea } from './vlTextarea'
export { default as vlCollapse } from './vlCollapse'
export { default as vlImages } from './vlImages'
// export { default as vlTimePicker } from './vlTimePicker'
//New Component import

//layout
export { default as vlRow } from '../layout/vlRow/'
export { default as vlCol } from '../layout/vlCol/'
